### ISSUE TITLE
Can I add this project to the featured project list of monaco-languagclient?

### ISSUE THREAD

**Issue by kaisalmen** [Guyutongxue/clangd-in-browser#2]
Hi @Guyutongxue this not an issue at all, but a request.
I stumbled over your work by coincidence and I think it is awesome. 👍🎉  

Can I add this to the featured project list of monaco-languagclient: https://github.com/TypeFox/monaco-languageclient?tab=readme-ov-file#featured-projects

I could also support you upgrading this project to the latest version of `monaco-languageclient` if you like.

**Comment by guyutongxue** [comment]
> Can I add this to the featured project list of monaco-languagclient: https://github.com/TypeFox/monaco-languageclient?tab=readme-ov-file#featured-projects

Sure! Thanks for your appreciation.

> I could also support you upgrading this project to the latest version of `monaco-languageclient` if you like.

PR is welcomed 😃

**Comment by kaisalmen** [comment]
PR will come after the new version is released. This will lift the stack to monaco-editor 0.48.0 and vscode api 1.89.0

**Comment by kaisalmen** [comment]
[Featured projects](https://github.com/TypeFox/monaco-languageclient?tab=readme-ov-file#featured-projects) have been updated. I close this issue and will open an update PR in the next couple of days.
