### ISSUE TITLE
ENOENT No such file or directory (errno 44)

### ISSUE THREAD

**Issue by Mw3y** [Guyutongxue/clangd-in-browser#7]
Hey @Guyutongxue,

I'm trying to use the clangd web assembly build but I'm having this error: 
![image](https://github.com/TypeFox/monaco-languageclient/assets/34509813/857c893b-a33e-460e-bc5e-883674e83a5b)

which comes from 
```ts
clangd.FS.writeFile('/workspace/main.cpp', '')
clangd.FS.writeFile(
  `/workspace/.clangd`,
  JSON.stringify({ CompileFlags: { Add: flags } })
)

```

I don't really know how to fix it...
I used the code provided in your repo.

Here's the code: 
- worker: https://haste.androz2091.fr/ubagajenil.typescript
- vue component: https://haste.androz2091.fr/otigumiyil.xml

**Comment by guyutongxue** [comment]
Seems that you need to create the directory `/workspace` inside the Emscripten FS before writing files. The API might be `FS.mkdir`, you can find more info [here](https://emscripten.org/docs/api_reference/Filesystem-API.html).

By the way, I'm using `/home/web_user` as the workspace folder and I need not to create it manually -- Emscripten created it already by default.

**Comment by Mw3y** [comment]
Works like a charm! Thank you! 

I didn't understand why it worked in your case 🤦🏻. I'll document myself on Emscripten!

Once again, thank you very much. Have a nice day!

**Comment by Mw3y** [comment]
Just wanted to ask another question: I'm trying to compile a java language server into wasm (it's a similar project to yours).
Do you know where I could start from/some good resources?

**Comment by guyutongxue** [comment]
> Just wanted to ask another question: I'm trying to compile a java language server into wasm (it's a similar project to yours).
> 
> Do you know where I could start from/some good resources?

Hmm... I've found that many Java language servers were written in Java ([listed here](https://microsoft.github.io/language-server-protocol/implementors/servers/)). So you need to found a proper way to "convert from Java to WASM". StackOverflow suggests that [teavm](https://github.com/konsoletyper/teavm) is a tool for transpiling Java bytecodes to WASM; you can have a try on that to compile a Java language Server into WebAssembly.

**Comment by Mw3y** [comment]
Thanks! Have a nice day!
